lstm:
  hidden_size: 128
  num_layers: 4
  dropout: 0.2

transformer:
  d_model: 64
  n_head: 8
  num_enc_layers: 2
  num_dec_layers: 2
  dim_feedforward: 128
  dropout: 0.2

ada_lstm:
  n_features: 13
  hidden_size: 256
  n_head: 1
  d_k: 64
  num_layers: 4
  dropout: 0.2