defaults:
  - _self_
  - data: base
  - model: base

model_name: lstm
eval_type: long_seq

device: cuda
weight_path: ./output/weights/lstm/${eval_type}/ws365_step1/best.pth

output_dir: ./output/plots/lstm/${eval_type}/ws365_step1

