defaults:
  - _self_
  - data: base
  - model: base

model_name: transformer
eval_type: long_seq

device: cuda
weight_path: ./output/weights/transformer/${eval_type}/ws365_step7/epoch_500.pth

output_dir: ./output/plots/transformer/${eval_type}/ws365_step7

